# See docs/examples
# http://doc.gitlab.com/ce/ci/quick_start/README.html
# http://doc.gitlab.com/ce/ci/yaml/README.html

image: golang:1.7.4-alpine

compile-go:
  script:
    - apk add --no-cache git
    - cd /builds/adi90x/go-rancher-gen
    - go get github.com/Sirupsen/logrus
    - go get github.com/BurntSushi/toml
    - go get github.com/rancher/go-rancher-metadata/metadata
    - go build 
    - ./go-rancher-gen  --version
    - mv go-rancher-gen rancher-gen
  artifacts:
    paths:
    - "rancher-gen"